# Generated by Django 5.2.8 on 2025-12-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'permissions': [('can_view_attendance', 'Can view attendance records'), ('can_edit_attendance', 'Can edit attendance records'), ('can_manage_attendance', 'Can manage attendance records')]},
        ),
    ]
