# Generated by Django 5.2.8 on 2025-12-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_department_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_employee_data', 'Can view employee data'), ('can_edit_employee_data', 'Can edit employee data'), ('can_manage_roles', 'Can manage user roles')]},
        ),
    ]
