# Generated by Django 5.2.8 on 2025-12-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_view_employee_data', 'Can view employee data'), ('can_edit_employee_data', 'Can edit employee data'), ('can_delete_employee_data', 'Can delete employee data'), ('can_manage_employee_data', 'Can manage employee data')]},
        ),
    ]
