# Generated by Django 5.2.8 on 2025-12-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
