# Generated by Django 5.2.8 on 2025-12-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_employee_data', 'Can view employee data'), ('can_edit_employee_data', 'Can edit employee data'), ('can_manage_roles', 'Can manage user roles')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin'), ('payroll_officer', 'Payroll Officer')], default='employee', max_length=20),
        ),
    ]
