# Generated by Django 5.2.8 on 2025-12-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_user_data', 'Can view user data'), ('can_edit_user_data', 'Can edit user data'), ('can_manage_roles', 'Can manage user roles')]},
        ),
    ]
