# Generated by Django 5.2.8 on 2025-12-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_salarystructure_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollrecord',
            options={'permissions': [('can_view_payroll_record', 'Can view payroll record'), ('can_edit_payroll_record', 'Can edit payroll record'), ('can_manage_payroll_record', 'Can manage payroll record')]},
        ),
        migrations.AlterModelOptions(
            name='salarystructure',
            options={'permissions': [('can_view_salary_structure', 'Can view salary structure'), ('can_edit_salary_structure', 'Can edit salary structure'), ('can_manage_salary_structure', 'Can manage salary structure')]},
        ),
    ]
