# Generated by Django 5.2.8 on 2025-12-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'permissions': [('can_view_audit_logs', 'Can view audit logs'), ('can_add_audit_logs', 'Can add audit logs'), ('can_manage_audit_logs', 'Can manage audit logs')]},
        ),
    ]
