# Generated by Django 5.2.8 on 2025-12-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': [('can_view_notifications', 'Can view notifications'), ('can_manage_notifications', 'Can manage notifications')]},
        ),
    ]
