# Generated by Django 5.2.8 on 2025-12-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave',
            options={'permissions': [('can_view_leave', 'Can view leave'), ('can_approve_leave', 'Can approve leave'), ('can_reject_leave', 'Can reject leave'), ('can_cancel_leave', 'Can cancel leave'), ('can_manage_leave_types', 'Can manage leave types')]},
        ),
    ]
